#ifndef BRIDGEFMTSPIHELPER_GLOBAL_H
#define BRIDGEFMTSPIHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#if defined(QT_BUILD_BRIDGEFMTSPIHELPER_LIB)
#  define BRIDGEFMTSPIHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BRIDGEFMTSPIHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // BRIDGEFMTSPIHELPER_GLOBAL_H
